package com.keystone.entity;

public enum ProjectType {
    RESIDENTIAL,
    COMMERCIAL,
    VILLA,
    PLOTTED_DEVELOPMENT,
    MIXED_USE,
    INDUSTRIAL,
    BUILDER_FLOOR,
    FARM_HOUSE,
    FLATS_APARTMENTS,
    INDEPENDENT_HOUSE,
    PENTHOUSE,
    RESIDENTIAL_PLOT,
    STUDIO_APARTMENT
}
