package com.keystone.entity;

public enum ProjectType {
    RESIDENTIAL,
    COMMERCIAL,
    VILLA,
    PLOTTED_DEVELOPMENT,
    MIXED_USE,
    INDUSTRIAL,
    // Residential Sub-categories
    BUILDER_FLOOR,
    FARM_HOUSE,
    FLATS_APARTMENTS,
    INDEPENDENT_HOUSE,
    PENTHOUSE,
    RESIDENTIAL_PLOT,
    STUDIO_APARTMENT,
    // Commercial Sub-categories
    AGRICULTURAL_LAND,
    BANQUET_HALL,
    BUSINESS_CENTER,
    COMMERCIAL_LAND,
    COMMERCIAL_SHOPS,
    FACTORY_INDUSTRIAL,
    HOTEL_RESTAURANT,
    INDUSTRIAL_LAND,
    OFFICE_SPACE,
    SHOWROOMS,
    WAREHOUSE_GODOWN
}
